### ISSUE TITLE
What we need to do to finish the report 6/2020

### ISSUE THREAD

**Issue by JoshHull** [immregistries/mqe#157]
Listing out the outstanding problems that need to be solved as of 6/2020 sprint: 

### DONE
- Add table for detection severity to match the ENUM. (**DONE**)
- Add the status to the code issues. (**DONE**)
- Add JDBC service for Provider report (**DONE**)

### TODO
- 

- [x]  Add Code status to FACILITY_CODE_COUNTS table, fill it in. (Josh will copy what he did for MESSAGE_CODE and **finish before End of Sprint**)
- [x]  Initialized at startup with the ENUM values (Hossam has an idea for this - a method annotated with "@PostConstruct") (Hossam will finish this **before End of Sprint**)
- [x]  Resolve the "Corrective Action" and additional data issues.  It's not currently unique for each Detection. It's Stored for EVERY detection in EVERY rule. There is an association between rule and detection.  how do we store that in the database?  Can we just do a 1 to 1 correlation with Detections? If we do that, we can store the MQE_CODE, and then the three text fields to say what to do. That data could be stored in a startup script, since it's not operational in the code like an ENUM.   DECISION: Josh and Hossam think we should go forward with storing it in the database, associated with an MQE code, rather than with the RULE.  (**NATHAN**)
- [x]   Figure out how to determine Adult/Child counts for the report, whether we query off the MESSAGE_METADATA table, or we have a new table for FACILITY to store it on the aggregate. (**JOSH**)

Finished Queries: 

- [x]  Get detections for the facility/date range (Top 10 ERROR severity) (Hossam will finish **before End of Sprint**)

**Add queries for the following parts of the report:** 
- [x]   Get "bad" codes for facility/date range (TOP 10 where status isn't valid) for first page of report (**HOSSAM**)
- [x]   Get vaccination codes (FULL LIST)  (how do we determine between historical/administered? Do we have this in the database? How do we count the vaccines by historical/admin and by type.  (don't worry about refusals, etc)
![image](https://user-images.githubusercontent.com/10420985/84317309-908f8880-ab3a-11ea-9c44-9e231c0dc54f.png)
- [ ]   Get Counts of vaccinations, patients, per age group and event. (FULL COUNT) 
![image](https://user-images.githubusercontent.com/10420985/84317245-748be700-ab3a-11ea-8e25-aeac2bee2912.png)

- [ ] Work on Generating real world examples for testing scenarios. (**JASON**)
- [ ] Evaluate the file upload efficiency - look at what speeds (milliseconds per message) we're seeing for the process, and determine where the slow points are in the code. The code got slower when we added something... I can't remember what it was, but that's part of this investigation. Might be that we switched to looking up severity from the database. (**JASON**)

**Comment by JoshHull** [comment]
Updated issue for 7/8 sprint work!

**Comment by nathanbunker** [comment]
I have made good progress on converting all the text into SQL. It's all in the SQL file, and now I'm trying to get MQE to start up. But I'm getting an exception, the table is not created. Looks like the problem is that the table is not being created before the SQL inserts are being run. Will check with the group. Once that is complete then I can commit.

**Comment by nathanbunker** [comment]
Changes have been committed for adding the concept of DetectionGuidance. I hope I've loaded it correctly. The schema.sql was the wrong file to put SQL in, this is only used to create schemas. The insert statements have to be put into data.sql. But I also got an error when I did this, saying the table was not yet created. So I moved them to a custom sql file and referenced them from within the DetectionGuidance class. Hopefully this instantiates correctly, but if not, at last MQE starts up without crashing.
